# Generated by Django 5.1.6 on 2025-02-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('registerID', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
